# Generated by Django 4.1.8 on 2023-12-27 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='Main_Image',
        ),
    ]
