# Generated by Django 4.1.8 on 2023-12-27 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0004_rename_image_product_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_spec',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecommers.product')),
                ('Product_Spcification', models.CharField(max_length=10000)),
                ('Product_ImageAlbum', models.FileField(upload_to='"ecommerse/files/')),
            ],
            bases=('ecommers.product',),
        ),
        migrations.AlterField(
            model_name='product',
            name='Main_Image',
            field=models.ImageField(upload_to='ecommerse/files/Main_Images'),
        ),
    ]
