# Generated by Django 4.1.8 on 2023-12-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0004_rename_image_product_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Main_Image',
            new_name='Image',
        ),
    ]
