# Generated by Django 4.1.8 on 2023-12-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0005_rename_main_image_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Specification',
            field=models.CharField(default=None, max_length=100000),
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(upload_to='ecommerse/files/Main_Images'),
        ),
    ]
