# Generated by Django 4.1.8 on 2023-12-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0006_product_specification_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Specification',
            field=models.TextField(default=None),
        ),
    ]
